### ISSUE TITLE
Installer not working on Amibian 1.5

### ISSUE THREAD

**Issue by beltoft** [henrikstengaard/hstwb-installer#31] opened 2020-02-20 08:23 UTC
Installer not working on new Amibian 1.5

Amibian dont have dialog command installed as default but can be installet via apt-get

next problem that i couldn't fix 
dir /home/amibian/amibian/amiberry/conf don't exist as conf file now are stored in ~/Amiga/conf

**Comment by henrikstengaard** [comment] 2020-02-22 07:41
Amibian 1.5 is only available as beta or closed behind donations. I don't have it at the moment.

But I'm going to make the paths configurable to support it

**Comment by beltoft** [comment] 2020-02-22 07:46
I can provide a copy of 1.5 if it will speed up the development

**Comment by henrikstengaard** [comment] 2020-02-22 07:51
That would certainly help and ensure it works with your setup. I will delete it after adding Amibian 1.5 support, then updating to latest HstWB Installer will include this. You can reach me at cyberhead97@gmail.com if needed

**Comment by beltoft** [comment] 2020-02-22 12:12
Shared with you on Google drive. Let me know if you got it

**Comment by henrikstengaard** [comment] 2020-02-22 17:18
@beltoft I got a shared Amibian15 folder, but it's empty

**Comment by beltoft** [comment] 2020-02-22 18:47
was out of space. should be there now

**Comment by henrikstengaard** [comment] 2020-02-22 19:15
got it, thanks. I will take a look at it

**Comment by henrikstengaard** [comment] 2020-02-23 12:07
Great news, I got almost everything updated to work with Amibian 1.5. Thanks again for providing the image, it really helped to me adding support and testing it works.

The only parts that aren't working yet are "Edit network settings, "Force Audio to HDMI" and "Force Audio to Jack" in Amibian setup menu.

The rest should be working and I have added installation of Dialog as well.

I need to do some more testing and tweaking to make it part of next HstWB Installer release.

You can help test by checking out a new amibian-15 branch with following steps:
1. cd ~/hstwb-installer
2. git reset --hard
3. git pull
4. git checkout amibian-15

**Comment by henrikstengaard** [comment] 2020-02-23 12:23
Note: I haven't been able to start HstWB Installer with JIT enabled for CPU. I'm not sure if this is related to issues with latest version of Amiberry included with Amibian v1.5 or some incompatibility with Kickstart v3.1.4 for A1200.

JIT worked fine with Amiberry and Chips UAE4ARM included with Amibian v1.4.1001.

Until now you probably need to avoid using JIT and stick to 25Mhz or fastest CPU speed, which means that installation process in HstWB Installer is really slow ... like really slow.

**Comment by beltoft** [comment] 2020-02-23 14:00
Did you update both amibian and amiberry? I Know there's been some bug fixes since the release. Maybe it will fix the jit problem. I will try to get time to test it today

**Comment by henrikstengaard** [comment] 2020-02-23 15:03
I didn't update Amibian or Amiberry. There might be updates that solves JIT. I will try that later today as well

**Comment by beltoft** [comment] 2020-02-23 18:12
I couldn't try it out today as I only have an 8GB sd card and there's not
enough free space on it to download hstwb image.

I will get a bigger one tomorrow and then test

søn. 23. feb. 2020 16.03 skrev Henrik Nørfjand Stengaard <
notifications@github.com>:

**Comment by henrikstengaard** [comment] 2020-02-23 20:18
@beltoft ahh, right. Installing HstWB Installer image requires 2GB disk space on your micro SD card, so a 16GB+ sized one is recommended.

I did further testing today and JIT works perfect after updating Amiberry to latest v3.1.2 even with CPU Speed set to Turbo. I installed Amiga OS 3.1.4 with update 3.1.4.1, ClassicWB FULL without any issues. Amiberry was updated by pulling latest source code and compile it.

**Comment by beltoft** [comment] 2020-02-29 10:43
Im testing it out now wth a 64gb sdcard and it's running. However i keep getting error in the amiga installation:
Volume AmigaOsDir is write protected

I can just press cancel and it will continue but its annoying

**Comment by beltoft** [comment] 2020-02-29 15:50
I can't get it to detect the amigaos3.9.iso in amigaosdir:

filename and hash is ok so i don't understand why the installer won't find it

**Comment by henrikstengaard** [comment] 2020-03-01 21:52
@beltoft I haven't tested much Amiga OS 3.9 installation using Amibian and Amiberry. HstWB Installer uses a device driver with in the emulator to mount the iso file virtually and this requires it's read/write to work. It could be a simple configuration issue.

I will do some testing with Amiga OS 3.9 iso on Amibian and reproduce the same issues to find a workable solution.

**Comment by henrikstengaard** [comment] 2020-03-06 20:37
I have been battling this issue back and forth over the last days with some improvement. Amiberry configurations have updated with read/write access to "amigaos" directory, which should fix the issue with mounting Amiga OS 3.9 iso by HstWB Installer.

However I haven't been able to test it successfully as I did an Amibian update and after this USB sticks are no longer automatically mounted. When I try to mount USB sticks manually, they are read only as amibian user and read/write as root.

Either I have to revert back to a clean Amibian 1.5 and retry or I need to update HstWB Installer to shadow copy "amigaos" directory to a temp directory.

I don't like any of those solutions and would prefer to get Amibian 1.5 to properly automount USB sticks with read/write again.

**Comment by beltoft** [comment] 2020-03-10 20:52
I reformatted my SD card and started over. updated amibian and amiberry and then started launcher.sh.but now the installer won't find my USB with the selfinstaller files. it is mounted at /media/usb. What to do?

**Comment by beltoft** [comment] 2020-03-11 14:14
if you need r/w on usb to move on add these 2 lines to /etc/usbmount/usbmount.conf overwrite the lines already in the conf file.

MOUNTOPTIONS="sync,noexec,nodev,noatime,nodiratime,nosuid,users,rw"
FS_MOUNTOPTIONS="-fstype=vfat,umask=000"

I asked the developer of amibian to add it in a future update

**Comment by beltoft** [comment] 2020-03-11 14:18
But even if the usb drive now is R/W hstwb installer still can't find the selfinstaller files. Where does the script look for the files? the usb is mounted in /media/usb

**Comment by henrikstengaard** [comment] 2020-03-11 14:33
Thanks for the tip about USB rw.

It looks for the self install files in /media/hstwb-self-install or /media/hstwb-installer. You can use HstWB menu and select Setup, HstWB Installer and Find HstWB Self Install. This iterates through /media mountpoints for ones containing hstwb-self-install.txt. The /media/hstwb symlink to the found mountpoints.

Please give that a try.

**Comment by beltoft** [comment] 2020-03-11 14:40
nope. it's not found even though i'm looking right at the txt file in /media/usb. strange part is that it found it in the first version i tried out

**Comment by henrikstengaard** [comment] 2020-03-11 14:50
Do you know if the USB stick/disk is mounted? What happens if you type "lsblk"?

**Comment by beltoft** [comment] 2020-03-11 15:51
Lsblk tells me sda is mounted at /media/usb0

**Comment by beltoft** [comment] 2020-03-11 17:46
if i hold "Find selfinstaller" i can see that its searching but it looks like is only look in /boot and not in /media

**Comment by henrikstengaard** [comment] 2020-03-11 18:50
I have made some changes to detection method in find HstWB self install. Have you tried updating by typing "cd ~/hstwb-installer" and "git pull"?

**Comment by beltoft** [comment] 2020-03-11 19:19
Did a pull and it says already up to date. So maybe there's an error in the detection?

**Comment by beltoft** [comment] 2020-03-14 15:15
I'm trying to go through what you have made and i can see that find self install is looking in the variable $usbmediapath but it doesn't looks like that variable is containing anything or if it is then it's the first fat32 partition it finds: /boot

I haven't been able to find where $usbmediapath is declared yet but im suspecting this is where the detection bug is

**Comment by beltoft** [comment] 2020-03-15 08:41
Ok I think I've found the bug
in  find-hstwb-self-install.sh the line 
`lsblk --list --paths --noheadings --output name,fstype,size,state,mountpoint | grep -e "vfat" -e "/media/" | awk '{print $4}'`
shoud be changed to 
`lsblk --list --paths --noheadings --output name,fstype,size,state,mountpoint | grep -e "vfat" -e "/media/" | awk '{print $5}'`

because the output of the lsblk command is
`/dev/sda       vfat   14.4G running /media/usb1
/dev/mmcblk0p1 vfat    256M         /boot
`

on the usb drive it have an extra column saying running and that was what in the output when using ` | awk '{print $4}'``

**Comment by henrikstengaard** [comment] 2020-03-15 09:49
@beltoft Nice, thanks. I will change it and push the change to fix it

**Comment by beltoft** [comment] 2020-03-15 09:58
Maybe investigate this a bit more because this change was working when I used my usb pen drive however not when I use my usb ssd disk

**Comment by henrikstengaard** [comment] 2020-03-15 10:44
I did change the USB detection from finding mounted devices that starts with /media/usb to any FAT32/16 device, so it will include boot in it's checking mounted devices. This must have caused detection issue.

**Comment by beltoft** [comment] 2020-03-15 11:39
Probably. And just forget what I said a out my ssd not being detected. It's not fat formatted

**Comment by beltoft** [comment] 2020-03-16 09:58
Ok I've run the installer without problems. Everything seems to work just fine. 3.9 iso was detected and all installed as it should. I've found out why USB drives was read only and fixed it and asked the developer of amibian to add the fix to next update. So I think you can close this issue  :)

**Comment by spikemorrissey** [comment] 2020-03-24 01:41
Hi, I would love this to work with Amibian 1.5 . Henrik, when do you think you will be able to update the installer please given that beltoft says he has managed to run the installer without problems?

**Comment by spikemorrissey** [comment] 2020-03-24 01:42
I have not been able to get it to work. I tried the new amibian branch but got 'ERROR: HstWB Installer root "" doesn't exist'

**Comment by cja2173** [comment] 2020-03-29 15:47
I too am having a problem with the 1.5 manual install. When I run the HstWB Image Setup cmd file I get the following: I don't understand what I am doing wrong.  Also what is the correct loacation and name so 3.9 iso file is found during run? must it be mounted like AmigaForever.iso?
![HstWBImageSetupCmderrorlog](https://user-images.githubusercontent.com/57053414/77853581-c5827500-71b2-11ea-8805-4671bf7f5be5.jpg)

**Comment by spikemorrissey** [comment] 2020-03-29 21:09
> I did change the USB detection from finding mounted devices that starts with /media/usb to any FAT32/16 device, so it will include boot in it's checking mounted devices. This must have caused detection issue.

Hi Henrik, 

Have you managed to fully resolve the issue please? I and many others are eagerly awaiting to use your installer with Amibian 1.5 Thank you!

**Comment by henrikstengaard** [comment] 2020-04-02 07:35
@spikemorrissey I'm going to see if I can get Amibian 1.5 support in a more stable state over the next days

**Comment by henrikstengaard** [comment] 2020-04-02 07:38
> I too am having a problem with the 1.5 manual install. When I run the HstWB Image Setup cmd file I get the following: I don't understand what I am doing wrong. Also what is the correct loacation and name so 3.9 iso file is found during run? must it be mounted like AmigaForever.iso?
> ![HstWBImageSetupCmderrorlog](https://user-images.githubusercontent.com/57053414/77853581-c5827500-71b2-11ea-8805-4671bf7f5be5.jpg)

From your screenshot an error occured due to WinUAE not being present in Windows registry. That's a bug I need to fix. But other than that it looks good from all the files it has detected. You seems to have Amiga OS 3.9 iso and boing bags, Amiga OS 3.1.4 and 3.1 adf files. Kickstart roms are also present, so I would expect that USB stick to work.

Have you tried installing HstWB Installer with it?

**Comment by henrikstengaard** [comment] 2020-04-02 12:51
> I have not been able to get it to work. I tried the new amibian branch but got 'ERROR: HstWB Installer root "" doesn't exist'

Could you please try running "rm -Rf ~/.hstwb-installer" and try installing again?

It the error still occurs afterwards, please try running "cat ~/.hstwb-installer/config.sh" and report back contents of this file.

**Comment by henrikstengaard** [comment] 2020-04-02 15:15
I have added a fix to usbmount.conf, which is applied during installation running install.sh. This solved my R/W issue with USB devices attached, but I still have to manually mount USB devices. For some reason USB devices aren't mounted automatically.

Mounting USB devices can be done manually by typing "hstwb", press enter and select System, Mount FAT32 devices. Afterwards HstWB, Setup, HstWB Installer, Find HstWB Self Install should detect attached USB device with HstWB self install files.

**Comment by spikemorrissey** [comment] 2020-04-02 20:47
Thank you for the reply. I managed to get the install going but despite having all the required files in the amigaos directory, the installer comes up with the the following message -

[Image.jpeg]
Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by spikemorrissey** [comment] 2020-04-02 21:04
![IMG_5428](https://user-images.githubusercontent.com/8340455/78299436-ed037580-7503-11ea-9ea4-acbde681085d.jpg)

**Comment by henrikstengaard** [comment] 2020-04-02 21:15
Strange it doesn't detect any valid iso or adf files.

I need more details about the files in amigaos directory you're trying to use.

From shell could you please run commands "ls -l /media/hstwb-self-install/amigaos" and "find /media/hstwb-self-install/amigaos -type f -exec md5sum '{}' \;" and attach screenshot of those?

Those two commands will list file details and md5 checksums of files you have in amigaos directory.

**Comment by spikemorrissey** [comment] 2020-04-02 21:38
How do I get into shell please as the raspberry pi just goes into a continuous loop of the install process?

**Comment by henrikstengaard** [comment] 2020-04-02 21:47
If you press F12 and quit Amiberry, then it should get you back a shell.

**Comment by cja2173** [comment] 2020-04-02 22:46
Henrik,
Thanks for deciphering the red portion.  I have been working on getting the full games library so I have not yet installed the stick. 


In an unrelated question I was wondering if you were considering adding midi support to the Amiberry emulator running under Amibian? I have no concept of how much work it would be so I can understand if you are not if it is horrendous.  I have posted some notes on the board relating a Linux midi tool that works with the Alsa packagehoping that it would help you find a solution.

In any event, thank you for your efforts and the code you have written. I came back for a second support contribution when I saw how good Amibian was.
  
On 4/2/2020 3:35:24 AM, Henrik Nørfjand Stengaard <notifications@github.com> wrote:
@spikemorrissey [https://github.com/spikemorrissey] I'm going to see if I can get Amibian 1.5 support in a more stable state over the next days

**Comment by spikemorrissey** [comment] 2020-04-02 23:41
l

> Strange it doesn't detect any valid iso or adf files.
> 
> I need more details about the files in amigaos directory you're trying to use.
> 
> From shell could you please run commands "ls -l /media/hstwb-self-install/amigaos" and "find /media/hstwb-self-install/amigaos -type f -exec md5sum '{}' ;" and attach screenshot of those?
> 
> Those two commands will list file details and md5 checksums of files you have in amigaos directory.

Thanks so much for helping, I would love to get this working! - The first command produced a result, the second command just brought up a prompt. Please see attached screenshot
![IMG_5430](https://user-images.githubusercontent.com/8340455/78309755-e41d9e80-7519-11ea-825c-9379385662b3.jpg)

**Comment by spikemorrissey** [comment] 2020-04-02 23:47
I'm not sure why the screenshots keep coming up the wrong way round however if you click on it a new window will come up with it the right way round!!!!

**Comment by henrikstengaard** [comment] 2020-04-03 07:40
Something is when wrong with your attached screenshot. I can't open it and get a broken image icon in your comment. Can you post it again?

Direction of the image is fine, i can manage to rotate it ;-)

**Comment by spikemorrissey** [comment] 2020-04-03 13:44
![IMG_5430](https://user-images.githubusercontent.com/8340455/78367206-b2471f00-758f-11ea-8663-f9a89f69b022.jpg)

**Comment by spikemorrissey** [comment] 2020-04-03 13:45
The image is showing up when I load Github in Chrome. I have uploaded the picture again. Thank you for your help with this!

**Comment by henrikstengaard** [comment] 2020-04-05 20:44
Thanks the image works now, might have been a glitch at github. 

The second command should not end with a quote ("). I just used those to indicate the command.

Please try again just with:
find /media/hstwb-self-install/amigaos -type f -exec md5sum '{}' ;

The files looks like the right ones, but I need to be sure by looking at md5 checksums

**Comment by henrikstengaard** [comment] 2020-04-05 20:58
I have given the scripts a lot of polish and testing this weekend with more features added and I just have to do a final test/reinstall on Amibian 1.5 before I officially release it. I expect to do that tomorrow evening

**Comment by spikemorrissey** [comment] 2020-04-05 23:52
I think I will wait for the grand release tomorrow then Henrik - thank you so much for all your work on this. I am very much looking forward to it!

**Comment by henrikstengaard** [comment] 2020-04-06 20:05
I have merged and released Amibian 1.5 support in master branch, so please retry installation of HstWB Installer for Amibian.

If you have been testing with amibian-15 branch either retry by switching back to master branch with following commands:
1. ```cd ~/hstwb-installer```.
2. ```git checkout master```.
3. ```git pull```.

I have added a lot of details about installation and use at Wiki page https://github.com/henrikstengaard/hstwb-installer/wiki/HstWB-Installer-for-Amibian.

So please give it a try again and note that Amiberry v3.1.2 or newer is required as it solves JIT issues.

**Comment by spikemorrissey** [comment] 2020-04-07 02:48
Thank you so much for all your work on this Henrik however although the installer is working and I have a 256 color screenmode the actual screen looks terrible - please can you advise?!
![IMG_5474](https://user-images.githubusercontent.com/8340455/78624859-a0e46800-7858-11ea-82f1-cf002cff82ec.jpg)

**Comment by henrikstengaard** [comment] 2020-04-07 08:28
Great, you got it installed and running. The lack of colors is more a Amiga OS or ClassicWB issue than it's related to HstWB Installer.

During installation of ClassicWB you will be presented with an option to select between icon colors: Default 16, Optimized 16 or Higher Colours. If you didn't select higher colours, then the icons and background image will appear ugly as ClassicWB has configure it to use low amount of colors and low colored background image. I'm not sure if this can be easily reverted, once it's already installed. As a start you could try changing background image from Workbench, Prefs and WBPattern to one with more than 16 colors, but that won't fix the icons.

**Comment by spikemorrissey** [comment] 2020-04-07 09:11
Thanks for the reply. The strange thing is, I did install higher colours and I still ended up with the ugly icons and background image. Do you think this is anything to do with the Raspberry Pi using Amiberry as opposed to UAE?

**Comment by spikemorrissey** [comment] 2020-04-07 22:44
Am I supposed to install Picasso 96? I must admit this has me stumped. Please could you advise?!

**Comment by spikemorrissey** [comment] 2020-04-07 23:37
I tried it again using the retro theme higher colors and os 3.9. The same thing happened again - an awful looking screen - do you think its anything to do with the installer mentioning that the display mode is UAE and Amibian uses Amiberry instead? - screenshots attached.
![IMG_5482](https://user-images.githubusercontent.com/8340455/78729112-2f172780-7907-11ea-835a-7da9e8f56d37.jpg)
![IMG_5483](https://user-images.githubusercontent.com/8340455/78729118-32aaae80-7907-11ea-8c0e-68dc122147af.jpg)

**Comment by spikemorrissey** [comment] 2020-04-08 01:00
I fixed it! I went to screen mode in wbprefs and selected pal high res laced, I then went into amiberry setup and selected line double mode and then rebooted and it fixed everything! - thank you for all your help with this Henrik!

**Closed** 2022-01-17 13:40 UTC
